---
openapi: "3.0.0"
info:
  description: "**Please be aware:**<br>*Testing in sandbox generates no costs for\
    \ the user. Sandbox access is automatic.*<br><br>Searching for locations on production\
    \ generates costs (geocoding), which are charged to the owner of the app.<br>**To\
    \ enable access to the production environment please send a request to International\
    \ Product Management (<a href='mailto:international-product-management@gls-group.com'>international-product-management@gls-group.com</a>)**<br><br><br>**The\
    \ maximum number of requests per day for this API is 10K in the production environment\
    \ and 100 in sandbox.**<br>Depending on the circumstances, the maximum value may\
    \ get increased for an app upon manual request.<br><br><br>This API retrieves\
    \ currently available GLS Points for parcel Drop-off, Returns, and C2C use cases\
    \ based on a provided address. Note that fields with value NULL may be omitted\
    \ (both in request and response).<br><br><hr><br><sub><sup> Corporate information:\
    \ <br> General Logistics Systems Germany GmbH & Co. OHG GLS Germany-Straße 1 -\
    \ 7 36286 Neuenstein Germany  +49(0)6677646907000 service@gls-germany.com  Authorised\
    \ representatives: Personally liable participators: GLS Beteiligungs GmbH, represented\
    \ by Saadi Al-Soudani, Dr. Karl Pfaff, Dr. Achim Dünnwald General Logistics Systems\
    \ B.V., represented by Dr. Karl Pfaff  Commercial Register No:  Local Court Bad\
    \ Hersfeld HRA 863 Sales Tax ID No: Sales tax identification-No. DE 812802911\
    \  Information on Online Dispute Resolution for consumers:   The EU commission\
    \ has set up an online platform for the online-resolution of disputes (\"ODR-platform\"\
    ). This platform serves as a contact point for extrajudicial resolutions of disputes\
    \ concerning contractual obligations, arising from online sales or services agreements.\
    \ Customers can reach the ODR-platform under the following [<sub><sup>link](http://ec.europa.eu/consumers/odr).\
    \ General obligation to provide information under Section 36 of the German Act\
    \ on Alternative Dispute Resolution in Consumer Matters (VSBG) Senders who contractually\
    \ make use of postal services of GLS Germany under generally accessible conditions\
    \ with regard to prices and services (e.g. via GLS ParcelShops, GLS-ONE and GLS\
    \ App) and their recipients, may call upon the regulatory authority as conciliation\
    \ body for the settlement of disputes with GLS Germany concerning rights and obligations\
    \ in the event of loss, theft or damage to postal items or the infringement of\
    \ their own rights to which they are entitled on the basis of a statutory ordinance\
    \ under Section 18 of the German Postal Act, if dispute settlement with GLS Germany\
    \ has previously been unsuccessful. If a consumer calls the conciliation body,\
    \ GLS Germany is obliged to take part in the dispute resolution procedure. Beyond\
    \ that, GLS Germany does not to take part in dispute resolution procedures before\
    \ a consumer conciliation body.  Competent consumer conciliation body:  Bundesnetzagentur\
    \ für Elektrizität, Gas, Telekommunikation, Post und Eisenbahnen Schlichtungsstelle\
    \ Post Tulpenfeld 4 53113 Bonn Internet: www.bundesnetzagentur.de  To the extent\
    \ participation is mandatory, GLS Germany will take part in a dispute resolution\
    \ procedure before this consumer conciliation body. <br> </sub></sup>"
  version: "1.0.0"
  title: "GLS Points for Drop-off (by address) API v1"
  termsOfService: "https://dev-portal.gls-group.net/terms"
servers:
- url: "https://api-sandbox.gls-group.net/parcel-shop-management/v2"
  description: "Sandbox (uses test data)"
- url: "https://api-qas.gls-group.net/parcel-shop-management/v2"
  description: "QAS (used for integration tests)"
- url: "https://api.gls-group.net/parcel-shop-management/v2"
  description: "Production (uses live data)"
paths:
  /gls-points-for-drop-off:
    get:
      tags:
      - "Parcel Shop retrieval"
      security:
      - OAuthSandbox: []
      summary: "Get multiple, available public GLS Points by address that are eligible\
        \ for dropping off a return parcel"
      description: "Retrieve public information of max. 5 GLS Points close to a given\
        \ address, which are available at least half of the next 14 days, i.e. they\
        \ are active, open, not on vacation or in maintenance and offer return drop\
        \ off service. And those shops need to be active, not on vacation or in maintenance\
        \ for 2 days after these 14 days. Optionally filtered by e.g. distance."
      operationId: "getGLSPointsForReturn"
      parameters:
      - name: "address"
        in: "query"
        description: "Address in human readable sequence to search for Out of Home\
          \ Locations in close proximity, typically contains a street name, a house\
          \ number, a zip code and a city name (but no country name)."
        required: true
        schema:
          type: "string"
          example: "Kölner Str. 3, 65760 Eschborn"
          minLength: 1
          maxLength: 255
      - name: "X-Message-ID"
        in: "header"
        description: "Used to correlate requests with their responses within a customer's\
          \ application, for logging and error reporting."
        required: false
        schema:
          type: "string"
          example: "123e4567-e89b-12d3-a456-426614174000"
      - name: "countryCode"
        in: "query"
        description: "A2 code of the Address' country."
        required: true
        schema:
          $ref: "#/components/schemas/CountryCode"
        example: "DE"
      - name: "limit"
        in: "query"
        description: "Maximum number of Out of Home Locations records to retrieve."
        required: false
        schema:
          type: "integer"
          default: 5
          minimum: 1
          maximum: 5
          example: 5
      - name: "distance"
        in: "query"
        description: "Radius in km to search available Out of Home Locations in, measured\
          \ from given \"address\"."
        required: false
        schema:
          type: "integer"
          default: 10
          minimum: 0
          maximum: 50
          example: 5
      - name: "extraAvailabilityDays"
        in: "query"
        description: "Number of days after the calculated availability period, where\
          \ the shop is not allowed to be on vacation, in maintenance or inactive."
        required: false
        schema:
          type: "integer"
          default: 2
          minimum: 0
          maximum: 100
          example: 2
      - in: "query"
        name: "resultCountryCodes"
        description: "Only return Out of Home Locations with an address in one of\
          \ the countries defined by these A2 codes."
        required: false
        schema:
          type: "array"
          items:
            $ref: "#/components/schemas/CountryCode"
          uniqueItems: true
        explode: false
      responses:
        "200":
          description: "OK."
          headers:
            X-RateLimit-Limit:
              schema:
                type: "integer"
              description: "Max Quota value."
            X-RateLimit-Remaining:
              schema:
                type: "integer"
              description: "Remaining Quota value for current App."
            X-RateLimit-Policy:
              schema:
                type: "string"
              description: "Policy when Quota is reset."
            X-RateLimit-Reset:
              schema:
                format: "int64"
                type: "integer"
              description: "The UTC time in milliseconds when the Quota expires and\
                \ new Quota interval starts."
            X-Message-ID:
              schema:
                type: "string"
              description: "Used to correlate requests with their responses within\
                \ a customer's application, for logging and error reporting."
            X-Valid-Country-Codes:
              schema:
                type: "string"
              description: "All A2 country codes for which OOH locations exist."
          content:
            application/json:
              schema:
                type: "object"
                required:
                - "data"
                - "limit"
                properties:
                  data:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/OutOfHomeLocation"
                  limit:
                    type: "number"
                    format: "integer"
                    description: "Maximum number of records retrieved."
                    example: 50
              example:
                data:
                - distance: 3.0437768
                  partnerId: "GLS_DE"
                  parcelShopId: "NewTest"
                  name: "Test"
                  type: "LOCKER"
                  address:
                    street: "GLS-Germany-Straße"
                    houseNumber: "1-7"
                    city: "Neuenstein"
                    zipCode: "36286"
                    province: "Hessen"
                    countryCode: "DE"
                    latitude: 51.90653
                    longitude: 12.52653
                    geocodeQualityLevel: "HOUSENUMBER"
                    additionalInfo: "Entrance via back alley"
                  externalContactDetails:
                    email: "meierandsons@gls-group.eu"
                    mobile: "+49987654321"
                  parcelHandlingRestriction:
                    canHandleTyres: "UNKNOWN"
                    canHandleHG: "UNKNOWN"
                    offersParcelCollection: "Y"
                    offersReturnDropOff: "Y"
                    offersLabelPurchase: "N"
                    offersPrepaidParcelDropOff: "N"
                  paymentMethods:
                  - "CASH"
                  parkingAvailable: "Y"
                  handicappedAccessAvailable: "UNKNOWN"
                  spokenLanguages:
                  - "ab"
                  - "en"
                  - "de"
                  vacations:
                  - startDate: "2023-12-12"
                    endDate: "2023-12-14"
                  openingDays:
                  - weekday: "MON"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                  - weekday: "TUE"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                  - weekday: "WED"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                  - weekday: "THU"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                  - weekday: "FRI"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                  - weekday: "SAT"
                    hours:
                    - openingTime: "05:00"
                      closingTime: "23:00"
                limit: 1
        "400":
          description: "Bad Request."
          headers:
            X-RateLimit-Limit:
              schema:
                type: "integer"
              description: "Max Quota value."
            X-RateLimit-Remaining:
              schema:
                type: "integer"
              description: "Remaining Quota value for current App."
            X-RateLimit-Policy:
              schema:
                type: "string"
              description: "Policy when Quota is reset."
            X-RateLimit-Reset:
              schema:
                format: "int64"
                type: "integer"
              description: "The UTC time in milliseconds when the Quota expires and\
                \ new Quota interval starts."
            X-Message-ID:
              schema:
                type: "string"
              description: "Used to correlate requests with their responses within\
                \ a customer's application, for logging and error reporting."
            X-Valid-Country-Codes:
              schema:
                type: "string"
              description: "All A2 country codes for which OOH locations exist."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  errors:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/GeneralError"
        "401":
          description: "Authorization header must contain a valid bearer token"
        "403":
          description: "User is not allowed to access resource."
        "408":
          description: "A Timeout has occurred while processing a request, please\
            \ retry."
          headers:
            X-RateLimit-Limit:
              schema:
                type: "integer"
              description: "Max Quota value."
            X-RateLimit-Remaining:
              schema:
                type: "integer"
              description: "Remaining Quota value for current App."
            X-RateLimit-Policy:
              schema:
                type: "string"
              description: "Policy when Quota is reset."
            X-RateLimit-Reset:
              schema:
                format: "int64"
                type: "integer"
              description: "The UTC time in milliseconds when the Quota expires and\
                \ new Quota interval starts."
            X-Message-ID:
              schema:
                type: "string"
              description: "Used to correlate requests with their responses within\
                \ a customer's application, for logging and error reporting."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  errors:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/GeneralError"
        "429":
          description: "User is neither allowed to exceed 10000 total requests to\
            \ Out of Home Location Finder API per day, nor 70 requests per second."
          headers:
            X-RateLimit-Limit:
              schema:
                type: "integer"
              description: "Max Quota value."
            X-RateLimit-Remaining:
              schema:
                type: "integer"
              description: "Remaining Quota value for current App."
            X-RateLimit-Policy:
              schema:
                type: "string"
              description: "Policy when Quota is reset."
            X-RateLimit-Reset:
              schema:
                format: "int64"
                type: "integer"
              description: "The UTC time in milliseconds when the Quota expires and\
                \ new Quota interval starts."
components:
  schemas:
    OutOfHomeLocation:
      type: "object"
      required:
      - "distance"
      - "partnerId"
      - "parcelShopId"
      - "name"
      - "address"
      properties:
        distance:
          type: "number"
          format: "float"
          description: "Distance between given \"address\" and Out of Home Location\
            \ address in km."
          example: 1.15
        partnerId:
          type: "string"
          description: "Identifier of the Partner, i.e. typically a GLS Organization\
            \ or another chain operating multiple Out of Home Locations."
          minLength: 1
          maxLength: 255
          pattern: "[a-zA-Z0-9_-]*"
          example: "GLS_DE"
        parcelShopId:
          type: "string"
          description: "Identifier of the Out of Home Location, unambiguous in the\
            \ Partner's namespace."
          minLength: 1
          maxLength: 255
          pattern: "[a-zA-Z0-9+_-]"
          example: "2764127573XYZ"
        parentParcelShopId:
          type: "string"
          description: "Identifier of the Out of Home Location's parent company, unambiguous\
            \ in the Partner's namespace."
          minLength: 1
          maxLength: 255
          pattern: "[a-zA-Z0-9+_-]"
          example: "2764127573XYZ"
        name:
          type: "string"
          maxLength: 255
          example: "Meier and Sons"
        type:
          $ref: "#/components/schemas/Type"
        parcelHandlingRestriction:
          $ref: "#/components/schemas/ParcelHandlingRestriction"
        externalContactDetails:
          type: "object"
          properties:
            phone:
              type: "string"
              maxLength: 255
              example: "+49 123 456789"
            email:
              type: "string"
              maxLength: 255
              example: "myemail@email.com"
          example:
            email: "meierandsons@gls-group.eu"
            mobile: "+49987654321"
        address:
          $ref: "#/components/schemas/Address"
        paymentMethods:
          type: "array"
          items:
            type: "string"
            enum:
            - "CASH"
            - "AMEX"
            - "VISA"
            - "DINERS"
            - "MASTERCARD"
            - "VPAY"
            - "MAESTRO"
            - "GIROCARD"
            - "APPLEPAY"
            - "GOOGLEPAY"
            - "UNKNOWN"
            description: "Payment options offered by the Out of Home Location to Customers."
            example: "CASH"
          example:
          - "CASH"
          - "MASTERCARD"
          default:
          - "UNKNOWN"
        parkingAvailable:
          type: "string"
          enum:
          - "Y"
          - "N"
          - "UNKNOWN"
          description: "Identifies whether parking spaces are available for Customers."
          default: "UNKNOWN"
        inMaintenanceFrom:
          type: "string"
          format: "YYYY-MM-dd"
          description: "Date in UTC from which the Parcel Shop is considered in maintenance\
            \ (i.e. not handles Parcels), activity starts at 00:00:00 local time.\
            \ An empty value indicates that the Parcel Shop is active. In maintenance\
            \ shops will show a message that they are in maintenance via the public\
            \ API, but are visible on the map."
          example: "2019-01-01"
        inMaintenanceTo:
          type: "string"
          format: "YYYY-MM-dd"
          description: "Date in UTC until the Parcel Shop is considered in maintenance\
            \ (i.e. not handles Parcels), activity ends at 23:59:59 local time. Must\
            \ be equal or larger than inMaintenanceFrom. An empty value indicates\
            \ that the Parcel Shop is in maintenance without any defined end date."
          example: "2019-12-31"
        handicappedAccessAvailable:
          type: "string"
          enum:
          - "Y"
          - "N"
          - "UNKNOWN"
          description: "Identifies whether handicapped access is available for Customers."
          default: "UNKNOWN"
        parcelExchangeTime:
          type: "string"
          format: "HH:MM"
          description: "Local time when Parcels typically get delivered to or get\
            \ collected from the Out of Home Location; useful to calculate thresholds\
            \ like \"bring your Parcel until 18h and it will be collected the same\
            \ day\"."
          example: "18:00"
        spokenLanguages:
          type: "array"
          items:
            type: "string"
            description: "Language (ISO 639-1 codes) spoken by clerks in the Out of\
              \ Home Location."
            enum:
            - "ab"
            - "aa"
            - "af"
            - "ak"
            - "sq"
            - "am"
            - "ar"
            - "an"
            - "hy"
            - "as"
            - "av"
            - "ae"
            - "ay"
            - "az"
            - "bm"
            - "ba"
            - "eu"
            - "be"
            - "bn"
            - "bh"
            - "bi"
            - "bs"
            - "br"
            - "bg"
            - "my"
            - "ca"
            - "ch"
            - "ce"
            - "ny"
            - "zh"
            - "cv"
            - "kw"
            - "co"
            - "cr"
            - "hr"
            - "cs"
            - "da"
            - "dv"
            - "nl"
            - "dz"
            - "en"
            - "eo"
            - "et"
            - "ee"
            - "fo"
            - "fj"
            - "fi"
            - "fr"
            - "ff"
            - "gl"
            - "ka"
            - "de"
            - "el"
            - "gn"
            - "gu"
            - "ht"
            - "ha"
            - "he"
            - "hz"
            - "hi"
            - "ho"
            - "hu"
            - "ia"
            - "id"
            - "ie"
            - "ga"
            - "ig"
            - "ik"
            - "io"
            - "is"
            - "it"
            - "iu"
            - "ja"
            - "jv"
            - "kl"
            - "kn"
            - "kr"
            - "ks"
            - "kk"
            - "km"
            - "ki"
            - "rw"
            - "ky"
            - "kv"
            - "kg"
            - "ko"
            - "ku"
            - "kj"
            - "la"
            - "lb"
            - "lg"
            - "li"
            - "ln"
            - "lo"
            - "lt"
            - "lu"
            - "lv"
            - "gv"
            - "mk"
            - "mg"
            - "ms"
            - "ml"
            - "mt"
            - "mi"
            - "mr"
            - "mh"
            - "mn"
            - "na"
            - "nv"
            - "nd"
            - "ne"
            - "ng"
            - "nb"
            - "nn"
            - "no"
            - "ii"
            - "nr"
            - "oc"
            - "oj"
            - "cu"
            - "om"
            - "or"
            - "os"
            - "pa"
            - "pi"
            - "fa"
            - "pl"
            - "ps"
            - "pt"
            - "qu"
            - "rm"
            - "rn"
            - "ro"
            - "ru"
            - "sa"
            - "sc"
            - "sd"
            - "se"
            - "sm"
            - "sg"
            - "sr"
            - "gd"
            - "sn"
            - "si"
            - "sk"
            - "sl"
            - "so"
            - "st"
            - "es"
            - "su"
            - "sw"
            - "ss"
            - "sv"
            - "ta"
            - "te"
            - "tg"
            - "th"
            - "ti"
            - "bo"
            - "tk"
            - "tl"
            - "tn"
            - "to"
            - "tr"
            - "ts"
            - "tt"
            - "tw"
            - "ty"
            - "ug"
            - "uk"
            - "ur"
            - "uz"
            - "ve"
            - "vi"
            - "vo"
            - "wa"
            - "cy"
            - "wo"
            - "fy"
            - "xh"
            - "yi"
            - "yo"
            - "za"
            - "zu"
            - "UNKNOWN"
          example:
          - "en"
          - "bg"
          default:
          - "UNKNOWN"
        vacations:
          type: "array"
          items:
            $ref: "#/components/schemas/Vacation"
          example:
          - startDate: "2020-12-12"
            endDate: "2021-01-01"
        openingDays:
          type: "array"
          items:
            $ref: "#/components/schemas/OpeningDay"
          example:
          - weekday: "MON"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
          - weekday: "TUE"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
          - weekday: "WED"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
          - weekday: "THU"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
          - weekday: "FRI"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
          - weekday: "SAT"
            hours:
            - openingTime: "05:00"
              closingTime: "23:00"
      example:
        distance: 3.0437768
        partnerId: "GLS_DE"
        parcelShopId: "NewTest"
        name: "Test"
        type: "LOCKER"
        address:
          street: "GLS-Germany-Straße"
          houseNumber: "1-7"
          city: "Neuenstein"
          zipCode: "36286"
          province: "Hessen"
          countryCode: "DE"
          latitude: 51.90653
          longitude: 12.52653
          geocodeQualityLevel: "HOUSENUMBER"
          additionalInfo: "Entrance via back alley"
        externalContactDetails:
          email: "meierandsons@gls-group.eu"
          mobile: "+49987654321"
        parcelHandlingRestriction:
          canHandleTyres: "UNKNOWN"
          canHandleHG: "UNKNOWN"
          offersParcelCollection: "Y"
          offersReturnDropOff: "Y"
          offersLabelPurchase: "N"
          offersPrepaidParcelDropOff: "N"
        paymentMethods:
        - "CASH"
        parkingAvailable: "Y"
        inMaintenanceFrom: "2025-03-05"
        inMaintenanceTo: "2025-03-07"
        handicappedAccessAvailable: "UNKNOWN"
        spokenLanguages:
        - "ab"
        - "en"
        - "de"
        vacations:
        - startDate: "2023-12-12"
          endDate: "2023-12-14"
        openingDays:
        - weekday: "MON"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
        - weekday: "TUE"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
        - weekday: "WED"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
        - weekday: "THU"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
        - weekday: "FRI"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
        - weekday: "SAT"
          hours:
          - openingTime: "05:00"
            closingTime: "23:00"
    Type:
      type: "string"
      enum:
      - "SHOPINSHOP"
      - "SHOP"
      - "LOCKER"
      - "KEEPER"
      - "UNKNOWN"
      description: "Details the type of the Out of Home Location, may be one of\n\
        * SHOP - Parcel Shop located in a GLS Depot or a GLS Shop\n* LOCKER - Automated\
        \ Parcel box system to collect or drop off Parcels\n* SHOPINSHOP - Parcel\
        \ Shop located within another store, e.g. convenience store\n* KEEPER - GLS\
        \ contracted trustworthy neighbours taking over parcel shop duties and offering\
        \ parcels pick-up\n* UNKNOWN\n"
      example: "SHOP"
    CountryCode:
      type: "string"
      enum:
      - "AF"
      - "AX"
      - "AL"
      - "DZ"
      - "AS"
      - "AD"
      - "AO"
      - "AI"
      - "AQ"
      - "AG"
      - "AR"
      - "AM"
      - "AW"
      - "AU"
      - "AT"
      - "AZ"
      - "BS"
      - "BH"
      - "BD"
      - "BB"
      - "BY"
      - "BE"
      - "BZ"
      - "BJ"
      - "BM"
      - "BT"
      - "BO"
      - "BQ"
      - "BA"
      - "BW"
      - "BV"
      - "BR"
      - "IO"
      - "BN"
      - "BG"
      - "BF"
      - "BI"
      - "CV"
      - "KH"
      - "CM"
      - "CA"
      - "KY"
      - "CF"
      - "TD"
      - "CL"
      - "CN"
      - "CX"
      - "CC"
      - "CO"
      - "KM"
      - "CG"
      - "CD"
      - "CK"
      - "CR"
      - "CI"
      - "HR"
      - "CU"
      - "CW"
      - "CY"
      - "CZ"
      - "DK"
      - "DJ"
      - "DM"
      - "DO"
      - "EC"
      - "EG"
      - "SV"
      - "GQ"
      - "ER"
      - "EE"
      - "SZ"
      - "ET"
      - "FK"
      - "FO"
      - "FJ"
      - "FI"
      - "FR"
      - "GF"
      - "PF"
      - "TF"
      - "GA"
      - "GM"
      - "GE"
      - "DE"
      - "GH"
      - "GI"
      - "GR"
      - "GL"
      - "GD"
      - "GP"
      - "GU"
      - "GT"
      - "GG"
      - "GN"
      - "GW"
      - "GY"
      - "HT"
      - "HM"
      - "VA"
      - "HN"
      - "HK"
      - "HU"
      - "IS"
      - "IN"
      - "ID"
      - "IR"
      - "IQ"
      - "IE"
      - "IM"
      - "IL"
      - "IT"
      - "JM"
      - "JP"
      - "JE"
      - "JO"
      - "KZ"
      - "KE"
      - "KI"
      - "KP"
      - "KR"
      - "KW"
      - "KG"
      - "LA"
      - "LV"
      - "LB"
      - "LS"
      - "LR"
      - "LY"
      - "LI"
      - "LT"
      - "LU"
      - "MO"
      - "MG"
      - "MW"
      - "MY"
      - "MV"
      - "ML"
      - "MT"
      - "MH"
      - "MQ"
      - "MR"
      - "MU"
      - "YT"
      - "MX"
      - "FM"
      - "MD"
      - "MC"
      - "MN"
      - "ME"
      - "MS"
      - "MA"
      - "MZ"
      - "MM"
      - "NA"
      - "NR"
      - "NP"
      - "NL"
      - "NC"
      - "NZ"
      - "NI"
      - "NE"
      - "NG"
      - "NU"
      - "NF"
      - "MK"
      - "MP"
      - "NO"
      - "OM"
      - "PK"
      - "PW"
      - "PS"
      - "PA"
      - "PG"
      - "PY"
      - "PE"
      - "PH"
      - "PN"
      - "PL"
      - "PT"
      - "PR"
      - "QA"
      - "RE"
      - "RO"
      - "RU"
      - "RW"
      - "BL"
      - "SH"
      - "KN"
      - "LC"
      - "MF"
      - "PM"
      - "VC"
      - "WS"
      - "SM"
      - "ST"
      - "SA"
      - "SN"
      - "RS"
      - "SC"
      - "SL"
      - "SG"
      - "SX"
      - "SK"
      - "SI"
      - "SB"
      - "SO"
      - "ZA"
      - "GS"
      - "SS"
      - "ES"
      - "LK"
      - "SD"
      - "SR"
      - "SJ"
      - "SE"
      - "CH"
      - "SY"
      - "TW"
      - "TJ"
      - "TZ"
      - "TH"
      - "TL"
      - "TG"
      - "TK"
      - "TO"
      - "TT"
      - "TN"
      - "TR"
      - "TM"
      - "TC"
      - "TV"
      - "UG"
      - "UA"
      - "AE"
      - "GB"
      - "US"
      - "UM"
      - "UY"
      - "UZ"
      - "VU"
      - "VE"
      - "VN"
      - "VG"
      - "VI"
      - "WF"
      - "EH"
      - "YE"
      - "ZM"
      - "ZW"
      description: "A2 code of the Out of Home Location's address' country."
      example: "DE"
    Address:
      type: "object"
      required:
      - "countryCode"
      - "city"
      - "street"
      - "latitude"
      - "longitude"
      properties:
        street:
          type: "string"
          maxLength: 255
          example: "GLS-Germany-Straße"
        houseNumber:
          type: "string"
          maxLength: 255
          example: "1-7"
        city:
          type: "string"
          maxLength: 255
          example: "Neuenstein"
        zipCode:
          type: "string"
          maxLength: 255
          example: "36286"
        province:
          type: "string"
          maxLength: 255
          example: "Hessen"
        countryCode:
          $ref: "#/components/schemas/CountryCode"
        latitude:
          type: "number"
          format: "float"
          minimum: -180
          maximum: 180
          description: "Latitude of the Out of Home Location's address."
          example: 50.90849
        longitude:
          type: "number"
          format: "float"
          minimum: -90
          maximum: 90
          description: "Longitude of the Out of Home Location's address."
          example: 9.58712
        geocodeQualityLevel:
          type: "string"
          enum:
          - "HOUSENUMBER"
          - "STREET"
          - "CITY"
          - "DISTRICT"
          - "UNKNOWN"
          example: "HOUSENUMBER"
        additionalInfo:
          type: "string"
          description: "Further (free-text) details on the Out of Home Location's\
            \ address."
          maxLength: 255
          example: "Entrance via back alley"
      example:
        street: "GLS-Germany-Straße"
        houseNumber: "1-7"
        city: "Neuenstein"
        zipCode: "36286"
        province: "Hessen"
        countryCode: "DE"
        latitude: 51.90653
        longitude: 12.52653
        geocodeQualityLevel: "HOUSENUMBER"
        additionalInfo: "Entrance via back alley"
    ParcelHandlingRestriction:
      type: "object"
      properties:
        maxParcelWeight:
          type: "number"
          format: "float"
          description: "Maximum weight (in kilogramms, kg) of a Parcel that the Out\
            \ of Home Location can handle."
          example: 3.5
        maxParcelLength:
          type: "number"
          format: "float"
          description: "Maximum length (in centimeters, cm) of a Parcel that the Out\
            \ of Home Location can handle."
          example: 100
        canHandleTyres:
          type: "string"
          example: "N"
          description: "Out of Home Location is equipped and has agreed to handle\
            \ Parcels with tyres."
          enum:
          - "Y"
          - "N"
        canHandleHG:
          type: "string"
          example: "N"
          description: "Out of Home Location is equipped and has agreed to handle\
            \ Parcels with Hazardous Goods."
          enum:
          - "Y"
          - "N"
        offersParcelCollection:
          type: "string"
          example: "Y"
          enum:
          - "Y"
          - "N"
          description: "Consignees can collect Parcels delivered to the Out of Home\
            \ Location, e.g. with ShopDeliveryService."
        offersReturnDropOff:
          type: "string"
          example: "Y"
          enum:
          - "Y"
          - "N"
          description: "Out of Home Location accepts Parcels with regular Return Label\
            \ or mobile Return Label (where offered), e.g. with ShopReturnService."
        offersLabelPurchase:
          type: "string"
          example: "Y"
          enum:
          - "Y"
          - "N"
          description: "Shippers can pay for Parcel shipping and buy a Label in the\
            \ Out of Home Location."
        offersPrepaidParcelDropOff:
          type: "string"
          example: "Y"
          enum:
          - "Y"
          - "N"
          description: "Shippers can drop off prepaid Parcels with regular Label or\
            \ mobile Label (where offered)."
      example:
        canHandleTyres: "UNKNOWN"
        canHandleHG: "UNKNOWN"
        offersParcelCollection: "Y"
        offersReturnDropOff: "Y"
        offersLabelPurchase: "N"
        offersPrepaidParcelDropOff: "N"
    PartnerId:
      type: "string"
      description: "Identifier of the Partner, i.e. typically a GLS Organization or\
        \ another chain operating multiple Out of Home Locations."
      minLength: 1
      maxLength: 255
      pattern: "[a-zA-Z0-9_-]"
      example: "GLS_DE"
    OpeningDay:
      type: "object"
      required:
      - "weekday"
      - "hours"
      properties:
        weekday:
          type: "string"
          enum:
          - "MON"
          - "TUE"
          - "WED"
          - "THU"
          - "FRI"
          - "SAT"
          - "SUN"
          description: "Day of week the record is valid for."
          example: "MON"
        hours:
          type: "array"
          items:
            type: "object"
            required:
            - "openingTime"
            - "closingTime"
            properties:
              openingTime:
                type: "string"
                format: "HH:MM"
                description: "Local time when the Out of Home Location opens."
                example: "08:00"
              closingTime:
                type: "string"
                format: "HH:MM"
                description: "Local time when the Out of Home Location closes."
                example: "16:00"
            example:
              openingTime: "08:00"
              closingTime: "16:00"
          example:
          - openingTime: "08:00"
            closingTime: "16:00"
      example:
        weekday: "MON"
        hours:
        - openingTime: "05:00"
          closingTime: "23:00"
    Vacation:
      type: "object"
      required:
      - "startDate"
      properties:
        startDate:
          type: "string"
          format: "YYYY-mm-dd"
          description: "Date (at 00:00:00) in UTC from which the Out of Home Location\
            \ is on vacation."
          example: "2020-09-10"
        endDate:
          type: "string"
          format: "YYYY-mm-dd"
          description: "Date (at 23:59:59) in UTC until which the Out of Home Location\
            \ is on vacation. May be null or omitted"
          example: "2020-09-18"
      example:
        startDate: "2020-12-12"
        endDate: "2021-01-01"
    GeneralError:
      type: "object"
      properties:
        type:
          description: "Machine-readable error type."
          type: "string"
          example: "MINMAX-CONSTRAINT-VIOLATED"
        fieldName:
          type: "string"
          description: "Name of field where error occurred."
          example: "limit"
        fieldValue:
          type: "string"
          description: "Field value where error occurred."
          example: "-12"
        documentationUrl:
          type: "string"
          description: "Link to further help on the error."
          example: "https://dev-portal.gls-group.net/error-codes?code=MINMAX-CONSTRAIN-VIOLATED"
  securitySchemes:
    OAuthSandbox:
      description: "This API can be used with OAuth 2 with the client credentials\
        \ grant flow. For production integration please use https://api.gls-group.net/oauth2/v2/token\
        \ to retrieve a production token. Note that below services require authentication\
        \ via OAuth Client Credentials flow - use our Authentication API to issue\
        \ a token."
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "https://api-sandbox.gls-group.net/oauth2/v2/token"
          scopes: {}
security:
- OAuthSandbox: []
